services:

  # mongo:
  #   image: mongo:8.2.1 # Official MongoDB image
  #   container_name: mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db # Persist database data
  
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5679:5672"
      - "15672:15672"
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=password

  user-services:
    build: ./user-services
    container_name: user-services
    volumes:
      - ./user-services:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    # depends_on:
      # - mongo

  task-services:
    build: ./task-services
    container_name: tasks-services
    volumes:
      - ./task-services:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  notification-services:
    build: ./notification-services
    container_name: notification-services
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq

volumes:
  rabbitmq:
  # mongo_data:
